// <auto-generated />
using System;
using FPIS_Projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FPIS_Projekat.Migrations
{
    [DbContext(typeof(ISContext))]
    partial class ISContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FPIS_Projekat.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.Device", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.Offer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("_ClientID")
                        .HasColumnType("int");

                    b.Property<int?>("_EmployeeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("_ClientID");

                    b.HasIndex("_EmployeeID");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.OfferItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("_DeviceID")
                        .HasColumnType("int");

                    b.Property<int?>("_OfferID")
                        .HasColumnType("int");

                    b.Property<int?>("_TariffPackageID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("_DeviceID");

                    b.HasIndex("_OfferID");

                    b.HasIndex("_TariffPackageID");

                    b.ToTable("OfferItems");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.PackageType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PackageTypes");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.TariffPackage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfMB")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfMessages")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfMinutes")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("_PackageTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("_PackageTypeID");

                    b.ToTable("TariffPackages");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.Offer", b =>
                {
                    b.HasOne("FPIS_Projekat.Models.Client", "_Client")
                        .WithMany()
                        .HasForeignKey("_ClientID");

                    b.HasOne("FPIS_Projekat.Models.Employee", "_Employee")
                        .WithMany()
                        .HasForeignKey("_EmployeeID");

                    b.Navigation("_Client");

                    b.Navigation("_Employee");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.OfferItem", b =>
                {
                    b.HasOne("FPIS_Projekat.Models.Device", "_Device")
                        .WithMany()
                        .HasForeignKey("_DeviceID");

                    b.HasOne("FPIS_Projekat.Models.Offer", "_Offer")
                        .WithMany("OfferItems")
                        .HasForeignKey("_OfferID");

                    b.HasOne("FPIS_Projekat.Models.TariffPackage", "_TariffPackage")
                        .WithMany()
                        .HasForeignKey("_TariffPackageID");

                    b.Navigation("_Device");

                    b.Navigation("_Offer");

                    b.Navigation("_TariffPackage");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.TariffPackage", b =>
                {
                    b.HasOne("FPIS_Projekat.Models.PackageType", "_PackageType")
                        .WithMany()
                        .HasForeignKey("_PackageTypeID");

                    b.Navigation("_PackageType");
                });

            modelBuilder.Entity("FPIS_Projekat.Models.Offer", b =>
                {
                    b.Navigation("OfferItems");
                });
#pragma warning restore 612, 618
        }
    }
}
